name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: foreman
          POSTGRES_PASSWORD: foreman
          POSTGRES_DB: foreman
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: theforeman/foreman
        ref: develop
        path: foreman
    - uses: actions/checkout@v3
      with:
        repository: theforeman/foreman_fog_proxmox
        path: foreman_fog_proxmox
    - uses: actions/checkout@v3
      with:
        repository: fog/fog-proxmox
        path: fog-proxmox
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Setup foreman
      env:
        PGHOST: 127.0.0.1
        PGDB: foreman
        PGPWD: foreman
        PGUSER: foreman
        RAILS_ENV: test
        DISABLE_SPRING: true
      working-directory: ./foreman 
      run: |
        sudo apt-get update && sudo apt-get -y install build-essential libpq-dev libsystemd-dev
        gem install bundler
        echo -n -e "gem 'foreman_fog_proxmox', :path => '../foreman_fog_proxmox'\n gem 'fog-proxmox', :path => '../fog-proxmox'\n gem 'simplecov'" > bundler.d/Gemfile.local.rb
        cp config/settings.yaml.test config/settings.yaml
        echo -n -e "test:\n adapter: postgresql \n port: 5432 \n database: foreman \n username: foreman \n password: foreman \n encoding: utf8 \n pool: 10" > config/database.yml
        cp config/model.mappings.example config/model.mappings
        cp config/ignored_environments.yml.sample config/ignored_environments.yml
        bundle config set without 'libvirt ovirt mysql2'
        bundle install --jobs 4 --retry 3
        bundle exec bin/rake db:migrate
        bundle exec bin/rake db:seed
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Setup node assets
      working-directory: ./foreman
      env:
        PGHOST: 127.0.0.1
        PGDB: foreman
        PGPWD: foreman
        PGUSER: foreman
        RAILS_ENV: test
        DISABLE_SPRING: true
      run: |
        npm install        
        bundle exec bin/rake assets:precompile locale:pack webpack:compile
    - name: Run test suite
      working-directory: ./foreman 
      env:
        PGHOST: 127.0.0.1
        PGDB: foreman
        PGPWD: foreman
        PGUSER: foreman
        RAILS_ENV: test
        DISABLE_SPRING: true
      run: |
        bundle exec bin/rake foreman_fog_proxmox:rubocop
        bundle exec bin/rake test:foreman_fog_proxmox
        
  publish:
      needs: [ build ]
      name: publish
      runs-on: ubuntu-latest
      if: contains(github.ref, '/tags/v')
      steps:
        - uses: actions/checkout@v3
        - name: Set up Ruby 2.7
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '2.7'
        - name: Publish to RubyGems
          env:
            GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          run: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
            printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
            gem build *.gemspec
            gem push *.gem
